### PR TITLE
Add some system stats sensors. System Load, MCU Load, Memory Used

### PR DESCRIPTION
**Pull request by linw1995**
Add some system stats sensors.

- System Load
- Memory Used Percent
- MCU Load/Awake

## Relative Graph metrics from fluidd

image

- MCU Load/Awake: https://github.com/fluidd-core/fluidd/blob/f3e4ac3c5c795051af26c6d195b6fd768c1e8906/src/store/chart_helpers.ts#L29-L32
- Memory Used Percent: https://github.com/fluidd-core/fluidd/blob/f3e4ac3c5c795051af26c6d195b6fd768c1e8906/src/store/chart_helpers.ts#L80-L86

## HA Results

image

### CODE REVIEW

**Comment by marcolivierarsenault** [comment]
Please make tests and Ruff pass.

There are pre made tasks in VSCode to run these if you want to do it locally

**Comment by linw1995** [comment]
> Please make tests and Ruff pass.
> 
> There are pre made tasks in VSCode to run these if you want to do it locally

@marcolivierarsenault I have adjusted the existing tests, and they now pass successfully.

**Comment by marcolivierarsenault** [comment]
Make sure you add test so we stay at 100% test (HA req.)

**Comment by marcolivierarsenault** [comment]
Hey, 

It's failing on my side 

```
2024-06-15 11:19:56.618 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up moonraker platform for sensor
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/workspaces/moonraker-home-assistant/custom_components/moonraker/sensor.py", line 298, in async_setup_entry
    await async_setup_optional_sensors(coordinator, entry, async_add_entities)
  File "/workspaces/moonraker-home-assistant/custom_components/moonraker/sensor.py", line 581, in async_setup_optional_sensors
    async_add_entities([MoonrakerSensor(coordinator, entry, desc) for desc in sensors])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/moonraker-home-assistant/custom_components/moonraker/sensor.py", line 758, in __init__
    self._attr_native_value = description.value_fn(self)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/moonraker-home-assistant/custom_components/moonraker/sensor.py", line 416, in <lambda>
    sensor.coordinator.data["status"][sensor.status_key]["last_stats"]["mcu_task_avg"]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
```

Trying to get more info to see what we should fix here

**Comment by marcolivierarsenault** [comment]
For some reason my version of Moonraker is not pushing stats 
image

**Comment by linw1995** [comment]
The `mcu.last_stats` is coming from Klipper. Maybe your printer needs to upgrade Klipper?

https://www.klipper3d.org/Status_Reference.html#mcu

**Comment by marcolivierarsenault** [comment]
oooo. got it. 

The issue is when the Printer is closed, when I turn the printer on the data is ok

**Review by marcolivierarsenault — APPROVED** [review]

**Comment by marcolivierarsenault** [comment]
PR causing faillure in prod... will revert

**Pull request merged**
