### PR TITLE
Add state_class property to relevant sensors to enable long-term statistics

### PR DESCRIPTION
**Pull request by leokeba**
Hi, I like use temp charts in my home assistant printers dashboard, however it does not work if the entity doesn't have its state_class property defined. It could also be done per-sensor with customize.yaml, but this seemed to be a common enough use-case to try suggesting a PR.

Hope this works for you, thanks.

### CODE REVIEW

**Comment by marcolivierarsenault** [comment]
@leokeba should we do this for all sensors?

**Comment by leokeba** [comment]
I think it would make sense for any sensor for which you might wanna see history charts. There is a relevant section in the docs : [](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)

**Comment by leokeba** [comment]
I found more relevant documentation here : [https://data.home-assistant.io/docs/statistics/](https://data.home-assistant.io/docs/statistics/)

So the main potential "downside" would be the space taken by the long term statistics storage. 24 data points a day is not going to be very significant for a few sensors, but maybe enough to not be over-zealous.

In any case, the user could always disable it if they are really space-constrained.

**Comment by marcolivierarsenault** [comment]
would you mind doing it for all sensor so we can have 1 clean pr for this

**Comment by leokeba** [comment]
I've use my best jugement to add the property to every sensor it might make sense for, what do you think ?

**Comment by marcolivierarsenault** [comment]
Will merge, 

This will be available in next release. or you can update to Main if you want to get it faster

**Pull request merged**
