### PR TITLE
Add support for TLS connections

### PR DESCRIPTION
**Pull request by ressu**
Currently the extension only allows connecting directly to moonraker or to a relay host which doesn't use HTTPS.

This change adds support to HTTPS connections to Moonraker.

### CODE REVIEW

**Comment by marcolivierarsenault** [comment]
This is really a good idea, I will review in the next few days. 
In the mean time, could you add info to the documentation about the new TLS option

**Review by marcolivierarsenault — COMMENTED** [review]
Code all 🍏 
🎩 : 🍏 

Only missing doc

**Comment by ressu** [comment]
Sure, I added very basic documentation. There isn't all that much to say about the connection dialog and the TLS option, but having a starting point is good.

**Review by marcolivierarsenault — APPROVED** [review]

**Comment by marcolivierarsenault** [comment]
Thank you @ressu

**Pull request merged**
